name: zzz
description: "Zzz â€” Premium Sleep Ritual App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^17.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  just_audio: ^0.9.40
  audio_service: ^0.18.15
  purchases_flutter: ^7.0.0
  go_router: ^14.0.0
  flutter_riverpod: ^2.5.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/free/
    - assets/sounds/premium/
